ss_jQuery(document).ready(function(){ss_jQuery(window).width();if("none"==ss_jQuery(".nav-full").css("display")){var a=ss_jQuery(".detachable-search-bar").detach();ss_jQuery("#insert-searchbar").append(a);ss_jQuery(".detachable-search-bar").addClass("mobile-search-bar");ss_jQuery(".detachable-search-bar div:first-child").addClass("mobile-search-bar-wrap");ss_jQuery(".btn-search-new").css("background-color","transparent");ss_jQuery(".btn-search-new span:first-child").addClass("mobile-icon-search");
ss_jQuery(".btn-search-new span:first-child").removeClass("icon-search")}else ss_jQuery(".btn-search-new").css("background-color","#ec010b");a=ss_jQuery(window).height();var b=ss_jQuery(".mobile-branding-header").height();a-=b+99;ss_jQuery(".nav-scroller").css("height",a+"px");0!=ss_jQuery(".nav-mobile:visible").length?ss_jQuery(".cmlla").addClass("new-cmlla"):ss_jQuery(".cmlla").removeClass("new-cmlla");-1==devBrowser.indexOf("msie")&&-1==devBrowser.indexOf("trident")||$(".locations-container, .mobile-search-btn").css("padding",
"37px 0 0 20px")});
ss_jQuery(window).resize(function(){ss_jQuery(window).width();var a=ss_jQuery(".detachable-search-bar").detach();"none"==ss_jQuery(".nav-full").css("display")?(ss_jQuery("#insert-searchbar").append(a),ss_jQuery(".detachable-search-bar").addClass("mobile-search-bar"),ss_jQuery(".detachable-search-bar div:first-child").addClass("mobile-search-bar-wrap"),ss_jQuery(".btn-search-new").css("background-color","transparent"),ss_jQuery(".btn-search-new span:first-child").addClass("mobile-icon-search"),ss_jQuery(".btn-search-new span:first-child").removeClass("icon-search")):
(ss_jQuery(".search-container").append(a),ss_jQuery(".btn-search-new").css("background-color","#ec010b"));a=ss_jQuery(window).height();var b=ss_jQuery(".mobile-branding-header").height();a-=b+99;ss_jQuery(".nav-scroller").css("height",a+"px");0!=ss_jQuery(".nav-mobile:visible").length?ss_jQuery(".cmlla").addClass("new-cmlla"):ss_jQuery(".cmlla").removeClass("new-cmlla")});
ss_jQuery(".mobile-search-btn, .mobile-search-toggle-wrap, .mobile-search-toggle").on("click touchstart",function(a){ss_jQuery(".mobile-search-bar").toggleClass("search-active");ss_jQuery("div.mobile-dropdown").hasClass("dropdown-active")&&(ss_jQuery(".menu-icon-bar").toggleClass("burger-active"),ss_jQuery(".mobile-dropdown").toggleClass("dropdown-active"));return!1});var devBrowser=window.navigator.userAgent,stringBrowser=String(devBrowser);devBrowser=stringBrowser.toLowerCase();
function disableDocumentScrolling(){if("fixed"!=document.documentElement.style.position){var a="undefined"!=typeof window.pageYOffset?window.pageYOffset:document.documentElement.scrollTop?document.documentElement.scrollTop:0;document.documentElement.style.position="fixed";document.documentElement.style.marginTop="-"+a+"px"}}
function enableDocumentScrolling(){if("fixed"==document.documentElement.style.position){-1!=devBrowser.indexOf("msie")||devBrowser.indexOf("trident");document.documentElement.style.position="static";var a=-1*parseFloat(document.documentElement.style.marginTop);document.documentElement.style.marginTop=null;window.scrollTo(0,a)}}
function goToNav(a,b){var c="navblock"+b;ss_jQuery("#navblock"+a).css("display","none");ss_jQuery("#"+c).fadeIn("fast",function(){});ss_jQuery("#"+c).css("display","block")}
ss_jQuery(".hamburger-menu").on("click touchstart",function(a){ss_jQuery(".menu-icon-bar").toggleClass("burger-active");ss_jQuery(".mobile-dropdown").toggleClass("dropdown-active");ss_jQuery(".mobile-search-bar").hasClass("search-active")&&ss_jQuery(".mobile-search-bar").toggleClass("search-active");ss_jQuery("div.mobile-dropdown").hasClass("dropdown-active")?(ss_jQuery("body").css("position","relative"),ss_jQuery("html").css("overflow","hidden"),disableDocumentScrolling()):(ss_jQuery("body").css("position",
""),ss_jQuery("html").css("overflow",""),enableDocumentScrolling(),ss_jQuery("#navblock0").css("display","block"),ss_jQuery("#navblock1, #navblock2, #navblock3, #navblock4, #navblock5, #navblock6, #navblock7, #navblock8, #navblock9, #navblock10, #navblock11, #navblock12, #navblock13, #navblock14, #navblock15, #navblock16, #navblock17, #navblock18, #navblock19, #navblock20, #navblock21, #navblock22, #navblock23, #navblock24, #navblock25, #navblock26, #navblock27, #navblock28, #navblock29, #navblock30, #navblock31, #navblock32").css("display",
"none"));ss_jQuery("nav-scroller").on("touchstart touchmove",function(){});return!1});ss_jQuery("#products-btn").mouseover(function(){ss_jQuery(".navbar-products-dropdown").css("display","block");ss_jQuery("#blinder-overlay").css("display","block")});ss_jQuery("#products-btn").mouseout(function(){ss_jQuery(".navbar-products-dropdown").css("display","none");ss_jQuery("#blinder-overlay").css("display","none")});
ss_jQuery("#browse-btn").mouseover(function(){ss_jQuery(".navbar-browse-dropdown").css("display","block");ss_jQuery("#blinder-overlay").css("display","block")});ss_jQuery("#browse-btn").mouseout(function(){ss_jQuery(".navbar-browse-dropdown").css("display","none");ss_jQuery("#blinder-overlay").css("display","none")});ss_jQuery("#brands-btn").mouseover(function(){ss_jQuery(".navbar-brands-dropdown").css("display","block");ss_jQuery("#blinder-overlay").css("display","block")});
ss_jQuery("#brands-btn").mouseout(function(){ss_jQuery(".navbar-brands-dropdown").css("display","none");ss_jQuery("#blinder-overlay").css("display","none")});
var openSubCats=function(a){a=ss_jQuery("#"+a.id).attr("name");ss_jQuery("#"+a).css("display","block");ss_jQuery("#tier2-"+a).toggleClass("active-tier2")},closeSubCats=function(a){a=ss_jQuery("#"+a.id).attr("name");if(!0===cancelClose)return!1;ss_jQuery("#"+a).css("display","none");ss_jQuery("#tier2-"+a).toggleClass("active-tier2");resetMenu()},openMenu=function(a){ss_jQuery("#"+a).css("display","block");ss_jQuery("#tier2-"+a).hasClass("active-tier2")||ss_jQuery("#tier2-"+a).toggleClass("active-tier2")},
closeMenu=function(a){ss_jQuery("#"+a).css("display","none");ss_jQuery("#tier2-"+a).hasClass("active-tier2")&&ss_jQuery("#tier2-"+a).toggleClass("active-tier2");resetMenu();cancelClose=!1},openSubBrands=function(a){category=ss_jQuery("#"+a.id).attr("name");ss_jQuery("#"+category+"-menu").css("display","block");ss_jQuery("#tier2-"+category).toggleClass("active-tier2")},closeSubBrands=function(a){category=ss_jQuery("#"+a.id).attr("name");if(!0===cancelClose)return!1;ss_jQuery("#"+category+"-menu").css("display",
"none");ss_jQuery("#tier2-"+category).toggleClass("active-tier2");resetMenu()},openBrandMenu=function(a){a=ss_jQuery("#"+a).attr("name");ss_jQuery("#"+a+"-menu").css("display","block");ss_jQuery("#tier2-"+a).hasClass("active-tier2")||ss_jQuery("#tier2-"+a).toggleClass("active-tier2")},closeBrandMenu=function(a){var b=ss_jQuery("#"+a).attr("name");ss_jQuery("#"+a).css("display","none");ss_jQuery("#tier2-"+b).hasClass("active-tier2")&&ss_jQuery("#tier2-"+b).toggleClass("active-tier2");resetMenu();cancelClose=
!1};function resetMenu(){0<$(".navbar-products-dropdown, .navbar-brands-dropdown").find(".active-tier2").length&&$(".active-tier2").toggleClass("active-tier2")}var config={over:function(){openSubCats(this)},out:function(){closeSubCats(this)},timeout:300},brandConfig={over:function(){openSubBrands(this)},out:function(){closeSubBrands(this)},timeout:300},cancelClose;$("#tier2-sewing").hoverIntent(config);$("#tier2-embroidery").hoverIntent(config);$("#tier2-quilting").hoverIntent(config);$("#tier2-serger").hoverIntent(config);
$("#tier2-industrial").hoverIntent(config);$("#tier2-furniture").hoverIntent(config);$("#tier2-vacuum").hoverIntent(config);$("#tier2-irons").hoverIntent(config);$("#tier2-brands").hoverIntent(config);$("#tier2-babylock").hoverIntent(brandConfig);$("#tier2-bernina").hoverIntent(brandConfig);$("#tier2-brother").hoverIntent(brandConfig);$("#tier2-handiquilter").hoverIntent(brandConfig);$("#tier2-viking").hoverIntent(brandConfig);$("#tier2-janome").hoverIntent(brandConfig);$("#tier2-juki").hoverIntent(brandConfig);
$("#tier2-pfaff").hoverIntent(brandConfig);$("#tier2-reliable").hoverIntent(brandConfig);$("#tier2-miele").hoverIntent(brandConfig);$("#tier2-oreck").hoverIntent(brandConfig);$("#tier2-dyson").hoverIntent(brandConfig);$("#tier2-singer").hoverIntent(brandConfig);$("#tier2-all").hoverIntent(brandConfig);
ss_jQuery("html").mousemove(function(){ss_jQuery(".tier3-content").mouseenter(function(){var a=ss_jQuery(this).attr("id");-1!==a.indexOf("menu")?openBrandMenu(a):openMenu(a);cancelClose=!0});ss_jQuery(".tier3-content").mouseleave(function(){var a=ss_jQuery(this).attr("id");-1!==a.indexOf("menu")?closeBrandMenu(a):closeMenu(a)})});$("a.shopping-bag").attr("href",shoppingCartURL);